// src/components/TaskCard.tsx
import styles from "@styles/task.module.css";
import { type Task } from "@utils/types.ts";
import { actions } from "astro:actions";
import { useEffect, useRef, useState } from "react";
import type { PropsWithChildren } from "react";
import { useStore } from "@nanostores/react";
import { findRoleTaskStatus } from "@stores/taskStore";

interface TaskCardProps {
  task: Task;
  journeyId: string;
  taskPrereq: boolean;
}

export default function TaskCard({
  task,
  journeyId,
  taskPrereq,
  children,
}: PropsWithChildren<TaskCardProps>) {
  const detailsDialogRef = useRef<HTMLDialogElement | null>(null);
  const completionDialogRef = useRef<HTMLDialogElement | null>(null);
  const [completedDescription, setCompletedDescription] = useState("");
  const [taskComplete, setTaskComplete] = useState(task.taskComplete);
  const isFindRoleTaskComplete = useStore(findRoleTaskStatus);

  // useEffect(() => {
  //   findRoleTaskStatus.set(taskPrereq);
  // }, [taskPrereq]);

  // a few tasks are specifically related to finding a role to apply for and doing the work to fill the application well. these we want to not let be completed unless you've already found a role - otherwise they don't make sense.
  const taskIdsWithPrereq = [5, 7, 8];

  const allowCompletion = taskIdsWithPrereq.includes(task.taskId)
    ? isFindRoleTaskComplete ?? false
    : true;

  const openDetailsDialog = () => {
    if (detailsDialogRef.current) detailsDialogRef.current.showModal();
  };

  const closeDetailsDialog = () => {
    if (detailsDialogRef.current) detailsDialogRef.current.close();
  };

  const openCompleteDialog = () => {
    if (detailsDialogRef.current) detailsDialogRef.current.close();
    if (completionDialogRef.current) completionDialogRef.current.showModal();
  };

  const closeCompleteDialog = (e: React.FormEvent) => {
    e.preventDefault();
    if (completionDialogRef.current) completionDialogRef.current.close();
  };

  const handleCompletion = async (e: React.FormEvent) => {
    e.preventDefault();

    const updatedTask = {
      ...task,
      taskComplete: true,
      taskCompleteNotes: completedDescription,
    };

    const { error } = await actions.completeTask({
      task: updatedTask,
      journeyId: journeyId,
    });

    if (!error) {
      setTaskComplete(true);
      if (task.taskAction.task === "Find a job to apply for") {
        findRoleTaskStatus.set(true);
      }
      if (completionDialogRef.current) completionDialogRef.current.close();
    } else {
      console.log({ error });
    }
  };

  return (
    <>
      <div className={styles.taskWrapper}>
        {!taskComplete ? (
          <button className={styles.openBtn} onClick={openDetailsDialog}>
            <p>{task.taskId}</p>
            <p>{task.taskAction.task}</p>
          </button>
        ) : (
          <div className={styles.completed}>{children}</div>
        )}
      </div>

      <dialog ref={detailsDialogRef}>
        <div>
          <button className={styles.closeBtn} onClick={closeDetailsDialog}>
            Close
          </button>
          {taskIdsWithPrereq.includes(task.taskId) && (
            <p>
              NOTE: This task can only be completed after you've done the 'Find
              a role to apply for' task!
            </p>
          )}
          <p>{task.taskAction.tip}</p>
          <button
            className={styles.doneBtn}
            onClick={openCompleteDialog}
            disabled={!allowCompletion}
          >
            Completed!
          </button>
        </div>
      </dialog>

      <dialog ref={completionDialogRef}>
        <form>
          <button className={styles.closeBtn} onClick={closeCompleteDialog}>
            Close
          </button>
          <label htmlFor="textarea">
            Write a reminder for future you on how you completed this task:
          </label>
          <textarea
            id="textarea"
            value={completedDescription}
            autoFocus={true}
            onChange={(event) => {
              setCompletedDescription(event.target.value);
            }}
          />
          <button
            className={styles.doneBtn}
            onClick={handleCompletion}
            disabled={completedDescription === ""}
          >
            Save note & complete
          </button>
        </form>
      </dialog>
    </>
  );
}

// app/components/TaskCard.vue
<script setup lang="ts">
const props = defineProps<{
  taskId: number;
  journeyId: string;
}>();

const journeyStore = useJourneyStore();

const detailsDialog = useTemplateRef("detailsDialog");
const completionDialog = useTemplateRef("completionDialog");
const completedDescription = ref("");

const currentTask = computed(() => {
  const task = journeyStore.currentJourney.taskList.find(
    (t) => t.taskId === props.taskId
  );

  if (!task) {
    throw new Error(`Task with id ${props.taskId} not found`);
  }

  return task;
}) satisfies ComputedRef<Task>;

const allowCompletion = computed(() => {
  if (!currentTask.value?.taskAction?.hasPrereq) return true;
  return journeyStore.findRoleTaskStatus;
});

function openDetailsDialog() {
  if (detailsDialog.value) detailsDialog.value.showModal();
}

function closeDetailsDialog() {
  if (detailsDialog.value) detailsDialog.value.close();
}

function openCompleteDialog() {
  if (detailsDialog.value) detailsDialog.value.close();
  if (completionDialog.value) completionDialog.value.showModal();
}

function closeCompleteDialog() {
  if (completionDialog.value) completionDialog.value.close();
}

async function handleTaskCompletion() {
  const updatedTask = {
    ...currentTask.value,
    taskComplete: true,
    taskCompleteNotes: completedDescription.value,
  };

  const { error } = await journeyStore.completeTask({
    task: updatedTask,
    journeyId: props.journeyId,
  });

  if (!error) {
    if (completionDialog.value) completionDialog.value.close();
  }
}
</script>

<template>
  <div class="taskWrapper">
    <button
      v-if="!currentTask.taskComplete"
      class="openBtn"
      @click="openDetailsDialog"
      type="button"
    >
      <p>{{ currentTask.taskId }}</p>
      <p>{{ currentTask.taskAction.task }}</p>
    </button>
    <div v-else class="completed">
      <SvgoStarFilled />
    </div>
  </div>

  <dialog ref="detailsDialog">
    <div>
      <button type="button" class="closeBtn" @click="closeDetailsDialog">
        Close
      </button>
      <p v-if="currentTask.taskAction.hasPrereq">
        NOTE: This task can only be completed after you've done the 'Find a role to apply for' task!
      </p>
      <p>{{ currentTask.taskAction.tip }}</p>
      <button
        type="button"
        class="doneBtn"
        @click="openCompleteDialog"
        :disabled="!allowCompletion"
      >
        Completed!
      </button>
    </div>
  </dialog>

  <dialog ref="completionDialog">
    <form>
      <button type="button" class="closeBtn" @click="closeCompleteDialog">
        Close
      </button>
      <label for="textarea"
        >Write a reminder for future you on how you completed this task:
      </label>
      <textarea id="textarea" autofocus v-model="completedDescription" />
      <button
        type="submit"
        class="doneBtn"
        @click.prevent="handleTaskCompletion"
        :disabled="completedDescription === ''"
      >
        Save note & complete
      </button>
    </form>
  </dialog>
</template>

<style scoped>
.taskWrapper {
  inline-size: 100%;
  block-size: 100%;
  display: grid;
  place-items: center;
}

.openBtn {
  background: none;
  color: inherit;
  border: none;
  inline-size: 100%;
  block-size: 100%;

  & p {
    font-size: var(--txt-sm);
  }

  &:focus {
    outline-offset: 0.25rem;
    border-radius: 0.125rem;
  }
}

.closeBtn {
  background: var(--dark-blue);
  color: var(--light-blue);
  justify-self: end;
  border-radius: 0.25rem;
  padding: 0.5rem;
}

.doneBtn {
  background: var(--dark-blue);
  color: var(--light-blue);
  border-radius: 0.25rem;
  padding: 0.5rem;

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
}

::backdrop {
  opacity: 0.85;
  background-color: var(--dark-blue);
}

dialog {
  background-color: var(--light-blue);
  border-radius: 0.25rem;
  border: 2px solid var(--dark-blue);
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  inline-size: 85dvw;

  & form,
  & div {
    display: grid;
    gap: 1.25rem;

    & textarea {
      border-radius: 0.25rem;
      padding: 0.25rem 0.375rem;
      border-color: var(--dark-blue);
    }
  }

  @media (width >= 1024px) {
    & {
      inline-size: 65dvw;
    }
  }

  @media (width >= 1280px) {
    & {
      inline-size: 50dvw;
    }
  }

  @media (width >= 1536px) {
    & {
      inline-size: 35dvw;
    }
  }
}

.completed {
  inline-size: 100%;
  block-size: 100%;
  background: var(--dark-blue);
  display: grid;
  place-items: center;

  & svg {
    inline-size: 2.5rem;
    block-size: 2.5rem;
    color: var(--light-blue);
  }
}
</style>
